# Site settings
title: Yuan Blog
SEOTitle: 苑苑的博客 | Yuan Blog
header-img: img/ home-bg-.jpg
email: wangyuan0928@outlook.com
description: "Every failure is leading towards success."
keyword: "Yuan Blog, 苑苑的博客, 苑苑, 读书"
url: "http://wangyuan0928.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/wangyuan0928/wangyuan0928.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "我歌月徘徊，我舞影零乱"
sidebar-avatar: /img/about-yuan.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    wangyuan0928
facebook_username:
jianshu_username:   283af8f474a4
#twitter_username:




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
disqus_username: wangyuan0928





# Analytics settings
# Baidu Analytics
ba_track_id:

# Google Analytics
ga_track_id: 'UA-xxxxxx-xx'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
  {
        title: "简书·Yuan",
        href: "http://www.jianshu.com/u/283af8f474a4"
    },{
        title: "Newsela",
        href: "https://newsela.com/#"
    }
]
